import Head from 'next/head';

import { Inter } from 'next/font/google';
import { MainSlider } from '@/components/MainSlider';
import { GroupProducts } from '@/components/GroupProducts';
import { Center } from '@chakra-ui/react';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Amazon Clone</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/amazonicon.png' />
      </Head>
      <main className=' bg-[#e3e6e6] relative md:h-[50rem] '>
        <div className='flex justify-center items-center '>
          <MainSlider />
        </div>

        <div className=' -mt-[7rem] z-50 absolute flex items-center justify-center w-full'>
          <GroupProducts />
        </div>
      </main>
    </>
  );
}
