import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import { MainSlider } from '@/components/MainSlider';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Amazon Clone</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/amazonicon.png' />
      </Head>
      <main>
        <div className='flex justify-center'>
          <MainSlider />
        </div>
      </main>
    </>
  );
}
